- name: test
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      replicas: 3
      replication: true
  clusterSelector:
    matchLabels:
      env: prod
  # Match cluster groups using selector
  # clusterGroupSelector:
  #   matchLabels:
  #     region: us-east
  # Match cluster group by name
  # clusterGroup: group1